local ok, transparent = pcall(require, 'transparent')
if not ok then
  return
end

transparent.setup {
  extra_groups = {
    'CmpItemMenu',
    'CmpNormal',
    'Diffview',
    'DiffviewNormal',
    'DiffviewCursorLine',
    'DiffviewStatusLine',
    'DiffviewSignColumn',
    'DiffviewEndOfBuffer',
    'WinSeparator',
    'TelescopeNormal',
    'TelescopeSelection',
    'TelescopeBorder',
    'TelescopePrompt',
    'TelescopeMultiSelection',
    'TreesitterContext',
    'TreesitterContextLineNumber',
    'FloatBorder',
    'NormalFloat',
    'StatusLine',
    'GitSignsAdd',
    'GitSignsChange',
    'GitSignsDelete',
    'NvimTreeNormal',
    'NvimTreeNormalNC',
    'NvimTreeStatusLine',
    'NvimTreeCursorLine',
    'NvimTreeWinSeparator',
    'NotifyERRORBorder',
    'NotifyWARNBorder',
    'NotifyINFOBorder',
    'NotifyDEBUGBorder',
    'NotifyTRACEBorder',
    'NotifyERRORBody',
    'NotifyWARNBody',
    'NotifyINFOBody',
    'NotifyDEBUGBody',
    'NotifyTRACEBody',
    'CratesNvimLoading',
    'CratesNvimVersion',
    'CratesNvimPreRelease',
    'CratesNvimYanked',
    'CratesNvimNoMatch',
    'CratesNvimUpgrate',
    'CratesNvimError',
    'DiagnosticVirtualTextOk',
    'DiagnosticVirtualTextHint',
    'DiagnosticVirtualTextInfo',
    'DiagnosticVirtualTextWarn',
    'DiagnosticVirtualTextError',
  },
}
